export const AUTHORIZATION_TOKEN_KEY = "auth-token";

export const TANSTACK_QUERY_KEYS = {
  CURRENT_USER: "current-user",
  CASE_LIST: "case-list",
  CASE_COUNT: "case-count",
  CASE_DETAILS: "case-details",
  CLIENT_DETAILS: "client-details",
  PAYMENT_INFORMATION_DETAILS: "payment-information-details",
  ALL_CLIENTS: "all-clients",
  FILTER_RESULTS: "filter-results",
  CLIENT_LIST: "client-list",
  CLIENT_COUNT: "client-count",
  ALL_CASES_TALLY_BY_STATUS: "all-cases-tally-by-status",
  DASH_COUNTS: "dash-counts",
  SIX_MOST_RECENT_CASES: "six-most-recent-cases",
  CASES_PER_CLIENT_TALLy: "cases-per-client-tally",
  RESOURCE_ACTIONS_LIST: "resource-actions-list",
  RESOURCE_ACTION_COUNT: "resource-action-count",
  ACCESS_POLICY_LIST: "access-policies-list",
  ACCESS_POLICY_COUNT: "access-policy-count",
  ACCESS_POLICY_DETAILS: "access-policy-details",
  ROLE_LIST: "role-list",
  ROLE_COUNT: "role-count",
  GROUP_LIST: "role-list",
  GROUP_COUNT: "role-count",
  GROUP_DETAILS: "group-details",
  USER_LIST: "user-list",
  USER_COUNT: "user-count",
};
